# Generated by Django 2.0.3 on 2021-05-03 23:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=100)),
                ('new_cases', models.IntegerField(default=0)),
                ('new_deaths', models.IntegerField(default=0)),
                ('date_confirmed', models.DateTimeField(default=django.utils.timezone.now)),
                ('facility', models.CharField(default='Nursing Home', max_length=100)),
            ],
        ),
    ]
