version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - echo "executing install phase"
            - echo "installing node js"
    pre_build:
        commands: 
            - echo "executing pre_build phase"
    build:
        commands:
            - echo "executing build phase"
            - echo "running tests phase"
            - grep -Fq "Coronavirus" Main_page/templates/Main_page/covidcases_home.html
    post_build:
        commands:
            - echo "executing post_build phase"
artifacts:
  files:
    - '**/*'

